# -*- coding: utf-8 -*-
"""Lista Exercícios Match Case

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b5zWJB964kINdZOTz_IWPCowyNy6WIU2

Exercício 1: Classificador de Idade
Escreva um programa que peça ao usuário sua idade e classifique-a usando match-case:
0-12: Criança
13-17: Adolescente
18-59: Adulto
60 ou mais: Idoso.
"""

idade = int(input('Digite a idade: '))

match idade:
  case i if idade <= 12:
    print('Criança')
  case i if idade <= 17:
    print('Adolecente')
  case i if idade <= 59:
    print('Adulto')
  case i if idade >= 60:
    print('Idoso')

"""Exercício 2: Conversor de Notas
Peça uma nota de 0 a 100 e converta em conceito com match-case:
90-100: A
80-89: B
70-79: C
60-69: D
Abaixo de 60: F.
"""

notas = float(input('Digite uma nota: '))

match notas:
  case n if notas <= 59:
    print('F')
  case n if notas <= 69:
    print('D')
  case n if notas <= 79:
    print('C')
  case n if notas <= 89:
    print('B')
  case n if notas <= 100:
    print('A')

"""Exercício 3: Calculadora de Descontos
Peça um valor de produto e o tipo de cliente (1-Comum, 2-Fidelidade, 3-VIP). Aplique desconto:
Comum: 5%
Fidelidade: 10%
VIP: 20%.
"""

print('desconto')
print('1 - Comum: 5%')
print('2 - Fidelidade: 10%')
print('3 - VIP: 20%.')

produto = float(input('Digite o valor do produto: '))

desconto = int(input('Difite o codigo: '))

match desconto:
  case 1:
    print(f'O valor do produto com desconto é {produto - (produto * 0.05)}')
  case 2:
    print(f'O valor do produto com desconto é {produto - (produto * 0.10)}')
  case 3:
    print(f'O valor do produto com desconto é {produto - (produto * 0.20)}')
  case _:
    print('Codigo inválido')

"""Exercício 4: Conversão de Temperatura
Receba uma temperatura e a unidade desejada (C-Fahrenheit, F-Celsius) e converta.
"""

print('--- Conversor ---')

i = float(input('Digite o valor que quer converter: '))

u = str(input('Digite para qual quer converter (c) Celcius e (f) Fahrenheit: ')).lower()

match u:
  case 'f':
    print(f'{i * 1.8 + 32}')
  case 'c':
    print(f'{(i - 32) / 1.8}')

"""Exercício 5: Verificador de Plural
Receba uma palavra e diga se termina com 's'. Use match-case para imprimir 'Plural' ou 'Singular'.
"""

palavra = str(input('Digite uma palavra e veja se ela é plural: ')).lower()

match palavra:
  case p if palavra.endswith('s'):
    print('plural.')
  case _:
    print('Singular')

"""Exercício 6: Tradutor de Cores:
Receba uma cor em inglês ('red', 'blue', 'green', etc.) e imprima o nome correspondente em português.
"""

tradutor = str(input('Digite umas das cores primerias em inglês: ')).lower()

match tradutor:
  case 'red':
    print('Vermelho')
  case 'blue':
    print('Azul')
  case 'green':
    print('Verde')
  case _:
    print('Cor inválida!')

"""Exercício 7: Calculadora de Frete
Peça o tipo de envio (1-Normal, 2-Expresso, 3-Sedex) e informe o tempo estimado de entrega.
"""

print('Frete Normal - 1')
print('Frete Expresso - 2')
print('Frete Sedex - 3')

calculadora = int(input('Digite o envio que deseja contratar: '))

match calculadora:
  case 1:
    print('Normal, entre 10 a 15 dias.')
  case 2:
    print('Expresso, entre 7 a 10 dias.')
  case 3:
    print('Sedex, entre 3 a 7 dias.')
  case _:
    print('Valor inválido')

"""Exercício 8: Simulador de Caixa Eletrônico
Peça ao usuário para escolher uma operação: (1-Saldo, 2-Saque, 3-Depósito) e imprima a ação
correspondente.
"""

escolha = int(input('1 - Saque, 2 - Saldo e 3 - Depósito'))

match escolha:
  case 1:
    print('Aguarde um dinheiro está sendo contado.')
  case 2:
    print('Seu saldo é R$: x,xxx.xx')
  case 3:
    print('Depósito realizado.')
  case _:
    print('Codigo inválido.')

"""Exercício 9: Sistema de Boas-vindas
Peça o turno (M-Matutino, V-Vespertino, N-Noturno) e cumprimente o usuário com match-case.
"""

escolha = str(input('Qual seu turno (M) (V) (N).')).upper()

match escolha:
  case 'M':
    print('Bom dia colaborador!')
  case 'V':
    print('Boa tarde colaborador!')
  case 'N':
    print('Boa noite colaborador!')
  case _:
    print('Não entendi o seu turno.')

"""Exercício 10: Calculadora de IMC
Peça peso e altura, calcule o IMC e classifique usando match-case:
<18.5: Abaixo do peso
18.5-24.9: Normal
25-29.9: Sobrepeso
30+: Obesidade.
"""

peso = float(input('Digite o seu peso: '))
altura = float(input('Digite a sua altura: '))

imc = peso / (altura * altura)

match imc:
  case i if imc < 18.5:
    print('Abaixo do peso.')
  case i if imc < 25:
    print('Normal.')
  case i if imc <= 29.9:
    print('Sobrepeso')
  case i if imc >= 30:
    print('Obesidade')

"""Exercício 11: Conversor de Moedas
Receba um valor em reais e a moeda desejada (1-Dólar, 2-Euro, 3-Libra). Converta usando taxas fictícias.
"""

print('--- Conversor ---')

i = float(input('Digite o valor que quer converter: '))

u = int(input('Digite para qual quer converter (1) Dolar, (2) euro ou (3) Libra: '))

match u:
  case 1:
    print(f'{i / 5.56:.2f}')
  case 2:
    print(f'{i / 6.45:.2f}')
  case 3:
    print(f'{i / 7.45:.2f}')

"""Exercício 12: Menu Interativo de Jogo
Crie um menu com opções: 1-Iniciar, 2-Carregar, 3-Créditos, 4-Sair. Exiba a opção escolhida.
"""

print("\n--- Menu do Jogo ---")
print("1 - Iniciar Novo Jogo")
print("2 - Carregar Jogo")
print("3 - Créditos")
print("4 - Sair")

escolha = input("Escolha uma opção (1-4): ")

match escolha:
  case '1':
    print("Iniciando novo jogo...")
  case '2':
    print("Carregando jogo salvo...")
  case '3':
    print("Exibindo créditos...")
  case '4':
    print("Saindo do jogo. Até mais!")

"""Exercício 13: Reconhecedor de Formato de Arquivo
Receba uma extensão de arquivo (.txt, .jpg, .py, etc.) e informe o tipo de arquivo (texto, imagem, código...).
"""

extensao = input("Digite a extensão do arquivo (ex: .txt, .jpg, .py): ").lower()

match extensao:
  case '.txt':
    print(f"A extensão '{extensao}' indica um arquivo de texto/documento.")
  case '.jpg':
    print(f"A extensão '{extensao}' indica um arquivo de imagem.")

  case '.py':
    print(f"A extensão '{extensao}' indica um arquivo de código/programação.")

  case _:
    print(f"A extensão '{extensao}' é de um tipo desconhecido para este programa.")

"""Exercício 14: Sistema de Notificações
Peça um nível de alerta (verde, amarelo, vermelho) e imprima a ação a ser tomada.
"""

nivel_alerta = input("Digite o nível de alerta (verde, amarelo ou vermelho): ").lower()

match nivel_alerta:
  case 'verde':
    print("VERDE: Tudo normal. Não há ações urgentes a serem tomadas.")
  case 'amarelo':
    print("AMARELO: Atenção! Monitore a situação de perto e esteja preparado para agir.")
  case 'vermelho':
    print("VERMELHO: Perigo iminente! Tome ações imediatas para garantir a segurança.")
  case _:
    print(f"Nível de alerta '{nivel_alerta}' inválido. Por favor, digite 'verde', 'amarelo' ou 'vermelho'.")

"""Exercício 15: Categorizador de Dias
Peça um dia da semana e diga se é útil ou final de semana.
"""

dia_da_semana = input("Digite um dia da semana (ex: segunda, sábado): ").lower()

match dia_da_semana:
  case 'segunda' | 'terça' | 'quarta' | 'quinta' | 'sexta':
    print(f"{dia_da_semana} é um dia útil.")
  case 'sábado' | 'domingo':
    print(f"{dia_da_semana} é um dia de final de semana!")
  case _:
    print(f"'{dia_da_semana}' não parece ser um dia da semana válido. Por favor, tente novamente.")

"""Exercício 16: Respostas de Bot de Atendimento
Com base na entrada do usuário (1-Suporte, 2-Vendas, 3-Reclamações), imprima uma resposta
automatizada.
"""

print("\n--- Central de Atendimento ---")
print("1 - Suporte Técnico")
print("2 - Vendas")
print("3 - Reclamações")
print("------------------------------")

escolha = input("Por favor, digite o número da opção desejada: ")

match escolha:
  case '1':
    print("Você selecionou Suporte Técnico. Por favor, aguarde enquanto conectamos você a um de nossos especialistas.")
  case '2':
    print("Você selecionou Vendas. Nossos consultores estão prontos para te atender.")
  case '3':
    print("Você selecionou Reclamações. Lamentamos qualquer inconveniente.")
  case _:
    print("Opção inválida. Por favor, digite 1, 2 ou 3 para continuar.")

"""Exercício 17: Classificação por Faixa Etária
Solicite a idade e classifique em: Bebê (0-2), Criança (3-12), Adolescente (13-17), Adulto (18-59), Idoso
(60+).
"""

idade = int(input("Por favor, digite sua idade: "))

match idade:
  case i if idade <= 2:
    print("Bebê.")
  case i if idade <= 12:
    print("Criança.")
  case i if idade <= 17:
    print("Adolescente.")
  case i if idade <= 59:
    print("Adulto.")
  case i if idade >= 60:
    print("Idoso.")
  case _:
    print("Idade inválida. Por favor, digite um número positivo.")

"""Exercício 18: Simulador de Nota Fiscal
Peça o tipo de produto (1-Alimento, 2-Bebida, 3-Eletrônico) e informe a alíquota de imposto.
"""

print("\n--- Simulador de Nota Fiscal ---")
print("Selecione o tipo de produto para saber a alíquota de imposto:")
print("1 - Alimento")
print("2 - Bebida")
print("3 - Eletrônico")

valor_produto = int(input('Digite o valor do produto: '))
tipo_produto = input("Digite o número correspondente ao tipo de produto: ")

match tipo_produto:
  case '1':
    print("Você selecionou 'Alimento'. A alíquota de imposto é de 5%.")
    imposto = valor_produto * 0.05
  case '2':
    print("Você selecionou 'Bebida'. A alíquota de imposto é de 15%.")
    imposto = valor_produto * 0.15
  case '3':
    print("Você selecionou 'Eletrônico'. A alíquota de imposto é de 10%.")
    imposto = valor_produto * 0.10
  case _:
    print("Opção inválida. Por favor, digite 1, 2 ou 3.")

"""Exercício 19: Conversor de Unidades
Permita ao usuário escolher uma conversão (1-km para mi, 2-Celsius para Fahrenheit, 3-kg para lb) e
execute.
"""

print("\n--- Conversor de Unidades ---")
print("Escolha o tipo de conversão:")
print("1 - Quilômetros (km) para Milhas (mi)")
print("2 - Celsius (°C) para Fahrenheit (°F)")
print("3 - Quilogramas (kg) para Libras (lb)")

escolha = input("Digite o número da opção desejada: ")

match escolha:
  case '1':
    km = float(input("Digite o valor em quilômetros: "))
    milhas = km * 0.621371
    print(f"{km} km equivalem a {milhas:.2f} milhas.")
  case '2':
    celsius = float(input("Digite a temperatura em Celsius: "))
    fahrenheit = (celsius * 9/5) + 32
    print(f"{celsius}°C equivalem a {fahrenheit:.2f}°F.")
  case '3':
    kg = float(input("Digite o peso em quilogramas: "))
    libras = kg * 2.20462
    print(f"{kg} kg equivalem a {libras:.2f} libras.")
  case _:
    print("Opção inválida. Por favor, digite 1, 2 ou 3.")

"""Exercício 20: Verificador de Operações Lógicas
Peça ao usuário para inserir uma operação (and, or, not) e descreva seu funcionamento com exemplos
simples.
"""

print("\n--- Verificador de Operações Lógicas ---")
print("Insira uma das operações lógicas para saber como funciona:")
print("AND")
print("OR")
print("NOT")
print("---------------------------------------")

operacao = input("Digite a operação (AND, OR, NOT): ").lower()

match operacao:
    case 'and':
        print("\nVocê escolheu a operação AND.")
        print("---")
        print("A operação AND (E) retorna VERDADEIRO se AMBAS as condições forem verdadeiras.")
        print("Se qualquer uma das condições (ou ambas) for falsa, o resultado é FALSO.")
        print("\nExemplos:")
        print("  Verdadeiro AND Verdadeiro = " + str(True and True))
        print("  Verdadeiro AND Falso     = " + str(True and False))
        print("  Falso AND Verdadeiro     = " + str(False and True))
        print("  Falso AND Falso          = " + str(False and False))
    case 'or':
        print("\nVocê escolheu a operação OR.")
        print("A operação OR (OU) retorna VERDADEIRO se QUALQUER UMA das condições for verdadeira.")
        print("Só retorna FALSO se AMBAS as condições forem falsas.")
        print("  Verdadeiro OR Verdadeiro = " + str(True or True))
        print("  Verdadeiro OR Falso     = " + str(True or False))
        print("  Falso OR Verdadeiro     = " + str(False or True))
        print("  Falso OR Falso          = " + str(False or False))
    case 'not':
        print("\nVocê escolheu a operação NOT.")
        print("A operação NOT (NÃO) inverte o valor lógico da condição.")
        print("Se a condição for verdadeira, NOT a torna falsa. Se for falsa, NOT a torna verdadeira.")
        print("  NOT Verdadeiro = " + str(not True))
        print("  NOT Falso     = " + str(not False))
    case _:
        print("Operação inválida. Por favor, digite 'AND', 'OR' ou 'NOT'.")